In [2]:
import numpy as np

In [3]:
# Unique parameters for this assignment (generated from your Student ID)

n0, n1, n2, n3, n4 = _, _, _, _, _

# Sample Data
x1 = np.array([0,            n4 * (3/2)]).reshape(-1,1)
x2 = np.array([n1,           n3 * (-1/2)]).reshape(-1,1)
x3 = np.array([n2 * (12/5),  n2]).reshape(-1,1)
x4 = np.array([n3 * (-7/10), n1 * (1/5)]).reshape(-1,1)
x5 = np.array([n4 * (1/5),   n0 * (-11/10)]).reshape(-1,1)

print("x1:\n", x1)
print()
print("x2:\n", x2)
print()
print("x3:\n", x3)
print()
print("x4:\n", x4)
print()
print("x5:\n", x5)   



x1:
 [[ 0.]
 [12.]]

x2:
 [[ 1.]
 [-3.]]

x3:
 [[0.]
 [0.]]

x4:
 [[-4.2]
 [ 0.2]]

x5:
 [[ 1.6]
 [-1.1]]


In [4]:
# Model Parameters

W = np.array([1,0]).reshape(-1,1)
μ = np.array([0,0]).reshape(-1,1)
Σ = np.array([[1,0],[0,1]])

print("W:\n", W)
print()
print('μ:\n', μ)
print()
print('Σ:\n', Σ)

W:
 [[1]
 [0]]

μ:
 [[0]
 [0]]

Σ:
 [[1 0]
 [0 1]]


## Question 1

$\hat{\mu} = \frac{1}{N}\sum^N_{n=1}x_n$

$x_n' = x_n - \hat{\mu}$

In [5]:
μ_update = np.mean([x1, x2, x3, x4, x5], axis=0)
μ_update

print('μ_update:\n', μ_update)

μ_update:
 [[-0.32]
 [ 1.62]]


In [6]:
x1_deviation = x1 - μ_update
x2_deviation = x2 - μ_update
x3_deviation = x3 - μ_update
x4_deviation = x4 - μ_update
x5_deviation = x5 - μ_update

print("x1':\n", x1_deviation)
print()
print("x2':\n", x2_deviation)
print()
print("x3':\n", x3_deviation)  
print()
print("x4':\n", x4_deviation)
print()
print("x5':\n", x5_deviation)

x1':
 [[ 0.32]
 [10.38]]

x2':
 [[ 1.32]
 [-4.62]]

x3':
 [[ 0.32]
 [-1.62]]

x4':
 [[-3.88]
 [-1.42]]

x5':
 [[ 1.92]
 [-2.72]]


## Question 2

Posterior probability density function of latent variables:

$\Sigma^{(z \mid x)} = (W^\top\Sigma^{-1}W+I)^{-1}$

$\mu_n^{z \mid x} = \Sigma^{(z \mid x)} W^\top\Sigma^{-1}x_n'$


In [7]:
Σ_inv = np.linalg.inv(Σ)
I = 1

Σ_zx = np.linalg.inv(W.T @ Σ_inv @ W + I)
print('Σ_zx (posterior covariance of latent variable z):\n', Σ_zx)

Σ_zx (posterior covariance of latent variable z):
 [[0.5]]


In [10]:
μ_zx_1 = Σ_zx @ W.T @ Σ_inv @ x1_deviation # z_1
μ_zx_2 = Σ_zx @ W.T @ Σ_inv @ x2_deviation # z_2
μ_zx_3 = Σ_zx @ W.T @ Σ_inv @ x3_deviation # z_3
μ_zx_4 = Σ_zx @ W.T @ Σ_inv @ x4_deviation # z_4
μ_zx_5 = Σ_zx @ W.T @ Σ_inv @ x5_deviation # z_5

print("μ_zx_1:\n", μ_zx_1)
print()
print("μ_zx_2:\n", μ_zx_2)
print()
print("μ_zx_3:\n", μ_zx_3)
print()
print("μ_zx_4:\n", μ_zx_4)
print()
print("μ_zx_5:\n", μ_zx_5)


μ_zx_1:
 [[0.16]]

μ_zx_2:
 [[0.66]]

μ_zx_3:
 [[0.16]]

μ_zx_4:
 [[-1.94]]

μ_zx_5:
 [[0.96]]


In [11]:
zzT_1 = Σ_zx + μ_zx_1 @ μ_zx_1.T
zzT_2 = Σ_zx + μ_zx_2 @ μ_zx_2.T
zzT_3 = Σ_zx + μ_zx_3 @ μ_zx_3.T
zzT_4 = Σ_zx + μ_zx_4 @ μ_zx_4.T
zzT_5 = Σ_zx + μ_zx_5 @ μ_zx_5.T

print("zzT_1:\n", zzT_1)
print()
print("zzT_2:\n", zzT_2)
print()
print("zzT_3:\n", zzT_3)
print()
print("zzT_4:\n", zzT_4)
print()
print("zzT_5:\n", zzT_5)

zzT_1:
 [[0.5256]]

zzT_2:
 [[0.9356]]

zzT_3:
 [[0.5256]]

zzT_4:
 [[4.2636]]

zzT_5:
 [[1.4216]]


## Question 3

$\begin{aligned}
\left\langle\boldsymbol{x}^{\prime} \boldsymbol{x}^{\prime \top}\right\rangle & =\sum_{n=1}^N \boldsymbol{x}_n^{\prime} \boldsymbol{x}_n^{\prime \top} \\
\left\langle\boldsymbol{z}\boldsymbol{z}^{\top}\right\rangle & =\sum_{n=1}^N\left\langle\boldsymbol{z}\boldsymbol{z}^{\top}\right\rangle_n \\
\left\langle\boldsymbol{x}^{\prime}\langle\boldsymbol{z}\rangle^{\top}\right\rangle & =\sum_{n=1}^N \boldsymbol{x}_n^{\prime}\langle\boldsymbol{z}\rangle^{\top}
\end{aligned}$

In [12]:
N = 5

xx_statistic = x1_deviation @ x1_deviation.T\
                + x2_deviation @ x2_deviation.T\
                + x3_deviation @ x3_deviation.T\
                + x4_deviation @ x4_deviation.T\
                + x5_deviation @ x5_deviation.T

zz_statistic = zzT_1 + zzT_2 + zzT_3 + zzT_4 + zzT_5 

xz_statistic = x1_deviation @ μ_zx_1.T\
                + x2_deviation @ μ_zx_2.T\
                + x3_deviation @ μ_zx_3.T\
                + x4_deviation @ μ_zx_4.T\
                + x5_deviation @ μ_zx_5.T

print("N:\n", N)
print()
print("<x'x'T>:\n", xx_statistic)
print()
print("<zzT>:\n", zz_statistic)
print()
print("<x'<zT>>:\n", xz_statistic)

N:
 5

<x'x'T>:
 [[ 20.688  -3.008]
 [ -3.008 141.128]]

<zzT>:
 [[7.672]]

<x'<zT>>:
 [[10.344]
 [-1.504]]


## Question 4

$\hat{\boldsymbol{W}}=\left\langle\boldsymbol{x}^{\prime}\langle\boldsymbol{z}\rangle^{\top}\right\rangle\left\langle\boldsymbol{z}^{\top}\right\rangle^{-1}$

$\hat{\boldsymbol{\Sigma}}=\frac{1}{N} \operatorname{diag}\left[\left\langle\boldsymbol{x}^{\prime} \boldsymbol{x}^{\prime \top}\right\rangle-\left\langle\boldsymbol{x}^{\prime}\langle\boldsymbol{z}\rangle^{\top}\right\rangle \hat{\boldsymbol{W}}^{\top}\right]$

In [13]:
W_hat = xz_statistic @ np.linalg.inv(zz_statistic)
Σ_hat = (1/N) * np.diag(np.diag(xx_statistic - xz_statistic @ W_hat.T))

print("W_hat:\n", W_hat)
print()
print("Σ_hat:\n", Σ_hat)

W_hat:
 [[ 1.34827946]
 [-0.19603754]]

Σ_hat:
 [[ 1.34827946  0.        ]
 [ 0.         28.16663191]]


## Question 5

$Σ_{update} = \Sigma + WW^\top$

In [14]:
Σ_before = Σ + W @ W.T
Σ_after = Σ_hat + W_hat @ W_hat.T

print("Σ_before:\n", Σ_before)
print()
print("Σ_after:\n", Σ_after)

Σ_before:
 [[2 0]
 [0 1]]

Σ_after:
 [[ 3.16613695 -0.26431339]
 [-0.26431339 28.20506262]]
